FitMe/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "FitMe Administration"
admin.site.index_title = "FitMe"
admin.site.site_title = "ADMIN PANEL"


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("FitMeApp.urls")),
    path("user/", include("user.urls")),
    path("oauth", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from decorator_include import decorator_include
from django.contrib.auth.decorators import login_required
from .decorators import manager_access

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index , name='login'),
    path('logout/', views.logout, name='logout'),

    path('managerDashboard/', views.managerDashboard, name='managerDashboard'),
    path('employeeDashboard/', views.employeeDashboard, name='employeeDashboard'),
    path('coachDashboard/', views.coachDashboard, name='coachDashboard'),

    path('employeeAttendance/', views.employeeAttendance, name='employeeAttendance'),
    path('coachAttendance/<int:pk>', views.coachAttendance, name='coachAttendance'),

    path('user/', decorator_include(manager_access,"user.urls",namespace="user")),
    path('schedule/', decorator_include(manager_access,"schedule.urls",namespace="schedule")),
    path('equipment/', decorator_include(login_required,"equipment.urls",namespace="equipment")),
    path('package/', decorator_include(manager_access,"package.urls",namespace="package")),
    path('member/', decorator_include(login_required,"member.urls",namespace="member")),
    path('coach/', decorator_include(login_required,"coach.urls",namespace="coach")),
    path('transaction/', decorator_include(manager_access,"transaction.urls",namespace="transaction")),
]

member/urls.py
from django.urls import path
from . import views

app_name = "member"

urlpatterns = [
    path('', views.index , name='index'),
    path('admin_view/', views.adminView , name='admin_view'),
    path('edit/<int:pk>', views.edit , name='edit'),
    path('payment_history/<int:pk>/<str:month>/<int:year>', views.paymentHistory , name='payment_history'),
    path('bill/', views.bill , name='bill'),
    path('pay/', views.pay , name='pay'),
    path('active/<int:pk>', views.active , name='active'),
    path('deactivate/<int:pk>', views.deactivate , name='deactivate'),
    path('delete/<int:pk>', views.delete , name='delete'),
]

myProject/myProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("MyApp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

member/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from package.models import Package

GENDER_CHOICES = [
    ('male', 'Male'),
    ('female', 'Female'),
]

# Create your models here.
class Member(models.Model):
    memberId = models.CharField(_("Member Id"),max_length=20,null=True,blank=True)
    name = models.CharField(_("Full Name"),max_length=50,null=True,blank=True)
    phone = models.CharField(_("Phone"),unique=True,max_length=15,blank=True,null=True)
    dob = models.DateField(_("Date of Birth"),null=True,blank=True)
    
    nid = models.CharField(_("NID"),max_length=20,null=True,blank=True)
    ref = models.CharField(_("Reference"),max_length=50,blank=True,null=True)
    address = models.TextField(_("Address"),null=True,blank=True)
    gender = models.CharField(_("Gender"),max_length=50, null=True,blank=True,choices=GENDER_CHOICES)

    package = models.ForeignKey(Package,on_delete=models.CASCADE,null=True,blank=True)

    due_payment = models.FloatField(_("Due Payment"),default=0)

    join_date = models.DateField(_("Joining Date"), null=True,blank=True)
    status =  models.BooleanField(_("Active Status"),default=True)


    def __str__(self) :
        return f'{self.name} - {self.dob}'

member/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.db.models import Q, Sum
from django.contrib import messages
from datetime import datetime
import datetime as dt

from .models import Member
from package.models import Package
from transaction.models import Debit, Bill
from user.models import MetaData
# Create your views here.

months = {
    'January': 1,
    'February': 2,
    'March': 3,
    'April': 4,
    'May': 5,
    'June': 6,
    'July': 7,
    'August': 8,
    'September': 9,
    'October': 10,
    'November': 11,
    'December': 12
}

def adminView(request):
    members = Member.objects.all().order_by("-due_payment")
    packages = Package.objects.all().order_by("-id")

    context = {
        'members':members,
        'packages':packages
    }
    return render(request,'member/admin_view.html',context)

def index(request):
    members = Member.objects.all().order_by("-due_payment")
    packages = Package.objects.all().order_by("-id")

    if request.method == "POST":
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        dob = request.POST.get("dob")
        nid = request.POST.get("nid")
        gender = request.POST.get("gender")
        packageId = request.POST.get("package")

        packageId = packageId.split(" ");
        packageId = packageId[0]
        address = request.POST.get("address")
        ref = request.POST.get("ref")
        amount = request.POST.get("amount")
        due = request.POST.get("due_amount")

        try:
            lastId = Member.objects.last().id
        except:
            lastId = 0

        package = Package.objects.get(id = packageId)
        # Get Current Month Name
        month = datetime.now().strftime("%B")
        # Get the current year
        year = datetime.now().year

        if int(amount) > package.price:
            memberDue = package.price - int(amount)
        else:
            memberDue = int(due) 

        member = Member.objects.create(
            name = name,
            phone = phone,
            dob = dob,
            nid = nid,
            gender = gender,
            package = Package.objects.get(id = packageId),
            address = address,
            ref = ref,
            due_payment = int(memberDue),
            memberId = "FKM-" + str(lastId+1),
            join_date = datetime.now()
        )

        Bill.objects.create(
            month = month,
            year=year,
            reason='admission',
            total_amount = package.price,
            payed_amount = amount,
            due_amount = due,
            member = member
        ) 

        timestamp = int(datetime.now().timestamp())
        meta = MetaData.objects.last()

        Debit.objects.create(
            trxId = "FK-TRX-" + str(timestamp),
            reason = "admission",
            amount = int(amount),
            date = datetime.now(),
            payed_by = member,
            received_by = request.user
        )
        meta.funds += int(amount)
        meta.save()

    context = {
        'members':members,
        'packages':packages
    }
    return render(request,'member/index.html',context)

def edit(request,pk):
    member = Member.objects.get(id = pk)
    packages = Package.objects.all().order_by("-id")
    bills = Bill.objects.filter(member = member).order_by("-id")
    month = datetime.now().strftime("%B")
    
    if request.method == "POST":
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        nid = request.POST.get("nid")
        packageId = request.POST.get("package")
        address = request.POST.get("address")
        ref = request.POST.get("ref")

        member.name = name
        member.phone = phone
        member.nid = nid
        member.ref = ref
        if member.package.id != int(packageId):
            member.package = Package.objects.get(id=packageId)
            member.due_payment += Package.objects.get(id=packageId).price
        member.address = address

        member.save()
        
    context = {
        'member':member,
        'packages':packages,
        'bills':bills,
        'month':month
    }
    return render(request,"member/edit.html",context)

def paymentHistory(request,pk,month,year):
    member = Member.objects.get(id = pk)
    payments = Debit.objects.filter(date__month=months[month],payed_by=member,date__year=year).order_by("-id")
    month = datetime.now().strftime("%B")

    context = {
        'member':member,
        'payments':payments,
        'month':month
    }
    return render(request,'member/payment_history.html',context)


def bill(request):
    members = Member.objects.filter(due_payment__gt =0,status=True).order_by("-due_payment")

    if request.method == "POST":
        search = request.POST.get("search")
        members = Member.objects.filter(Q(name__icontains=search) | Q(memberId__icontains=search), due_payment__gt=0)

    context = {
        'members':members,
    }
    return render(request,"member/bill.html",context)

def getPreviousMonth(request):
    # Get the current date and time
    current_date = datetime.now()

    # Calculate the previous month
    previous_month = current_date.replace(day=1) - dt.timedelta(days=1)

    # Get the previous month's name
    previous_month_name = previous_month.strftime("%B")

    # Print the previous month's name
    return previous_month_name

def pay(request):
    # Get Current Month Name
    month = datetime.now().strftime("%B")
    # Get the current year
    year = datetime.now().year

    if request.method == "POST":
        memberId = request.POST.get("memberId")
        amount = request.POST.get("amount")

        total_amount = amount
        try:
            timestamp = int(datetime.now().timestamp())
            meta = MetaData.objects.last()

            member = Member.objects.get(memberId = memberId)
            if member.status == False:
                messages.error(request,"Member Profile is deactivated")
                return redirect("/member/bill/")
            
            member.due_payment -= int(amount)

            flag = True

            try:
                prev_month = getPreviousMonth(request)
                prev_bill = Bill.objects.get(member = member, month = prev_month,due_amount__gt = 0)
            except:
                flag = False

            updateThisMonth = True

            if flag:
                left_amount = float(amount) - prev_bill.due_amount
                
                if left_amount <= 0:
                    prev_bill.due_amount -= float(amount)
                    updateThisMonth = False
                else:
                    amount = left_amount
                    prev_bill.due_amount = 0

                prev_bill.save()


            if updateThisMonth:
                bill = Bill.objects.get(member = member, month = month)
                if float(amount) > bill.due_amount:
                    bill.advanced_amount = float(amount) - bill.due_amount
                    bill.due_amount = 0
                else:
                    bill.due_amount -= float(amount)

                bill.payed_amount += float(total_amount)

                bill.save()
                

            Debit.objects.create(
                trxId = "FK-TRX-" + str(timestamp),
                reason = "package_fee",
                amount = int(total_amount),
                date = datetime.now(),
                payed_by = member,
                received_by = request.user
            )
            meta.funds += int(amount)
            meta.save()
            member.save()

        except:
            messages.error(request,"Wrong Member Id")
    return redirect("/member/bill/")

def deactivate(request,pk):
    member = Member.objects.get(id = pk)
    member.status = False
    member.save()
    return redirect("/member/")

def active(request,pk):
    member = Member.objects.get(id = pk)
    member.status = True
    member.save()
    return redirect("/member/")

def delete(request,pk):
    Member.objects.get(id = pk).delete()
    return redirect("/member/")

templates/member/admin_view.html
{% extends "../base.html" %}
{% load custom_filters %}

{% block body %}
<!-- component sections starts  -->
<div class="conponentSection p-5 sm:ml-64 bg-gray-200">
  <div class="componentWrapper">
    <!-- List section starts  -->
    <div class="bg-gray-50 p-4 shadow-xl rounded-md">
      <div class="relative overflow-x-auto h-[28rem]">
        <table class="w-full">
          <thead class="text-sm uppercase bg-blue-900 text-gray-50 text-center">
            <tr>
              <th scope="col" class="px-6 py-3">Member ID</th>
              <th scope="col" class="px-6 py-3">Name</th>
              <th scope="col" class="px-6 py-3">phone</th>
              <th scope="col" class="px-6 py-3">Package</th>
              <th scope="col" class="px-6 py-3">Join Date</th>
              <th scope="col" class="px-6 py-3">Status</th>
              <th scope="col" class="px-6 py-3">Due/Advanced</th>
              <th scope="col" class="px-6 py-3">View</th>
            </tr>
          </thead>
          <tbody>
            {% for member in members %}
            <tr class="bg-white border text-sm text-center">
              <td class="px-6 py-4">{{member.memberId}}</td>
              <td class="px-6 py-4">{{member.name}}</td>
              <td class="px-6 py-4">{{member.phone}}</td>
              <td class="px-6 py-4">{{member.package.name}}</td>
              <td class="px-6 py-4">{{member.join_date}}</td>
              <td class="px-6 py-4">{{member.status}}</td>
              <td class="px-6 py-4">
                {% if member.due_payment < 0 %}
                {{ member.due_payment|abs_val }} Taka Advanced
                  {% else %}
                  {{member.due_payment}} Taka Due
                {% endif %}
                </td>
              <td class="px-6 py-4"><a class="underline" href="{% url "member:edit" member.id %}">View</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock body %}
{% block js %}
<script>
  $("document").ready(() => {
    // Package Select
    $("#package").change(e => {
      let price = e.target.value;
      price = price.split(' ');
      price = price[2];
      $("#payable_amount").val(`${price}`);
      $("#amount").removeAttr("disabled");
      $("#amount").val("");

      document.querySelectorAll(".due_amount").forEach(item => {
        item.value = `${price}`;
      })
    });
    // Amount Change
    $("#amount").on('input', (e) => {
      let pa = $("#payable_amount").val();
      let a = e.target.value;
      let val = (Number(pa) - Number(a)) > 0 ? (Number(pa) - Number(a)) : 0;
      document.querySelectorAll(".due_amount").forEach(item => {
        item.value = `${val}`;
      })
    })
  })
</script>
{% endblock js %}

templates/member/bill.html
{% extends "../base.html" %}

{% block body %}
<div class="conponentSection p-5 sm:ml-64 bg-gray-200">
    <div class="componentWrapper">
        <!-- Entry Form starts  -->
        <div class="formSection bg-white p-4 rounded shadow-md mb-4">
            <h3 class="text-2xl font-bold mb-4">Search</h3>
            <form method="post">
                {% csrf_token %}
                <div class="grid gap-4">
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="search" type="text"
                        placeholder="Search For Member" />
                    <div>
                        <button class="bg-blue-900 text-white font-bold py-2 px-4 w-full" type="submit">
                            Search
                        </button>
                    </div>
                </div>
            </form>
        </div>
        <div class="bg-gray-50 p-4 shadow-xl rounded-md mt-4">
            <h3 class="text-2xl font-semibold mb-4">Payment Due Member List</h3>
            <div>
                <div class="relative overflow-x-auto">
                    <table class="w-full">
                        <thead class="text-sm uppercase bg-blue-900 text-gray-50 text-center">
                            <tr>
                                <th scope="col" class="px-6 py-3">Member Id</th>
                                <th scope="col" class="px-6 py-3">Name</th>
                                <th scope="col" class="px-6 py-3">Phone</th>
                                <th scope="col" class="px-6 py-3">Package</th>
                                <th scope="col" class="px-6 py-3">Due</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for member in members %}
                            <tr class="bg-white border text-sm text-center">
                                <td class="px-6 py-4">{{member.memberId}}</td>
                                <td class="px-6 py-4">{{member.name}}</td>
                                <td class="px-6 py-4">{{member.phone}}</td>
                                <td class="px-6 py-4">{{member.package.name}}</td>
                                <td class="px-6 py-4">{{member.due_payment}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="bg-gray-50 p-4 shadow-xl rounded-md mt-4">
            {% for message in messages %}
            <div class="py-4 text-red-600 font-bold">
                {{message}}
            </div>
            {% endfor %}
            <h3 class="text-2xl font-semibold mb-4">Pay Package Bill</h3>
            <form class="grid grid-cols-2 gap-4" method="post" action="/member/pay/" autocomplete="off">
                {% csrf_token %}
                <!-- Member Id -->
                <input class="border w-full p-4 leading-tight bg-slate-100" name="memberId" type="text"
                    placeholder="Member Id" required list="memberList" />
                <datalist id="memberList">
                    {% for member in members %}
                        <option value="{{member.memberId}}"> {{member.name}} | {{member.package.name}} | {{member.status}} </option>
                    {% endfor %}
                </datalist>
                <!-- Amount -->
                <input class="border w-full p-4 leading-tight bg-slate-100" name="amount" type="number"
                    placeholder="Amount" required />
                <div class="col-span-2">
                    <button class="bg-blue-900 text-white font-bold py-2 px-4 w-full" type="submit">
                        Pay
                    </button>
                </div>
        </div>
    </div>
</div>
</div>

{% endblock body %}

templates/member/edit.html
{% extends "../base.html" %}
{% load custom_filters %}

{% block body %}
   <!-- component sections starts  -->
   <div class="conponentSection p-5 sm:ml-64 bg-gray-200">
    <div class="componentWrapper">
        <!-- Entry Form starts  -->
        <div class="formSection bg-white p-4 rounded shadow-md mb-4">
            <div class="flex justify-between">
                <h3 class="text-2xl font-bold mb-4">Member Details</h3>
            </div>
            <form class="grid grid-cols-3 gap-4" method="post">
                {% csrf_token %}
                <!-- Col 1 -->
                <div class="grid gap-2">
                    <!-- Member Id -->
                    <input class="border w-full p-4 leading-tight bg-slate-100 disabled:cursor-not-allowed disabled:bg-slate-300" name="memId" type="text" placeholder="Member Id" disabled value="{{member.memberId}}" />
                    <!-- Name -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="name" type="text" placeholder="Name" required value="{{member.name}}" />
                    <!-- NID -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="nid" type="text" placeholder="NID" required value="{{member.nid}}" />
                </div>
                <!-- Col 2 -->
                <div class="grid gap-2">
                    <!-- Phone -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="phone" type="tel" placeholder="Phone" required value="{{member.phone}}" />                 
                    <!-- Reference -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="ref" type="text" value="{{member.ref}}" />                     
                </div>
                <!-- Col 3 -->
                <div class="grid gap-3">      
                     <!-- Package  -->
                     <select name="package" class="border w-full p-4 leading-tight bg-slate-100">
                      <option hidden>Select a package</option>
                      {% for package in packages %}
                        <option {% if package.id == member.package.id %}selected{% endif %} value="{{package.id}}">{{package.name}}</option>
                      {% endfor %}
                    </select>     
                    <!-- Address -->
                    <textarea class="border w-full p-4 leading-tight bg-slate-100" name="address" placeholder="Address" required >{{member.address}}</textarea>
                </div>
                <div class="col-span-2">
                    <button
                      class="bg-blue-900 text-white font-bold py-2 px-4 w-full"
                      type="submit">
                      Update
                    </button>
                </div>
                <div>
                    {% if member.status %}
                        <a href="{% url "member:deactivate"  member.id %}" class="bg-yellow-900 text-white font-bold py-2 px-4 w-full inline-block text-center cursor-pointer">
                            Deactivate Member
                        </a>
                        {% else %}
                        <a href="{% url "member:active"  member.id %}" class="bg-green-900 text-white font-bold py-2 px-4 w-full inline-block text-center cursor-pointer">
                            Activate Member
                        </a>
                    {% endif %}
                </div>
                {% comment %} <div>
                    <a href="{% url "member:delete" member.id %}" class="bg-red-900 text-white font-bold py-2 px-4 w-full inline-block text-center cursor-pointer">
                        Delete Member
                    </a>
                </div> {% endcomment %}
            </form>
        </div>
          <!-- Transaction History -->
          <section class="bg-gray-50 w-full p-4 shadow-xl rounded-md mt-4">
            <div class="flex justify-between">
                <h3 class="text-2xl font-bold">Monthly Transaction History</h3>
                <span>
                    {% if member.due_payment < 0 %}
                    Total Advanced: 
                    {{ member.due_payment|abs_val }} 
                      {% else %}
                      Total Due: 
                      {{member.due_payment}}
                    {% endif %}
                    Taka ({{month}})
                </span>
            </div>
            <div class="relative overflow-x-auto mt-4">
                <table class="w-full">
                    <thead class="text-sm uppercase bg-blue-900 text-gray-50 text-center">
                        <tr>
                            <th scope="col" class="px-6 py-3">Month</th>
                            <th scope="col" class="px-6 py-3">Reason</th>
                            <th scope="col" class="px-6 py-3">Total Amount</th>
                            <th scope="col" class="px-6 py-3">Payed Amount</th>
                            <th scope="col" class="px-6 py-3">Due Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for bill in bills %}
                        <tr class="bg-white border text-sm text-center">
                            <td class="px-6 py-4"><a class="underline" href="{% url "member:payment_history" member.id bill.month bill.year %}">{{bill.month}}</a></td>
                            <td class="px-6 py-4">{{bill.reason}}</td>
                            <td class="px-6 py-4">{{bill.total_amount}}</td>
                            <td class="px-6 py-4">{{bill.payed_amount}}</td>
                            <td class="px-6 py-4"><a class="underline" href="{% url "member:bill" %}">{{bill.due_amount}}</a</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </section>
    </div>
  </div>
{% endblock body %}

templates/member/index.html
{% extends "../base.html" %}
{% load custom_filters %}

{% block body %}
<!-- component sections starts  -->
<div class="conponentSection p-5 sm:ml-64 bg-gray-200">
  <div class="componentWrapper">
    <!-- Entry Form starts  -->
    <div class="formSection bg-white p-4 rounded shadow-md mb-4">
      <h3 class="text-2xl font-bold mb-4">New Member Form</h3>
      <form class="grid grid-cols-4 gap-4" method="post">
        {% csrf_token %}
        <!-- Col 1 -->
        <div class="grid gap-2">
          <!-- Name -->
          <input class="border w-full p-4 leading-tight bg-slate-100" name="name" type="text" placeholder="Name"
            required />
          <!-- DOB  -->
          <input class="border w-full p-4 leading-tight bg-slate-100" name="dob" type="date" required />
          <!-- NID -->
          <input class="border w-full p-4 leading-tight bg-slate-100" name="nid" type="text" placeholder="NID"
            required />
        </div>
        <!-- Col 2 -->
        <div class="grid gap-2">
          <!-- Phone -->
          <input class="border w-full p-4 leading-tight bg-slate-100" name="phone" type="tel" placeholder="Phone"
            required />
          <!-- Reference -->
          <input class="border w-full p-4 leading-tight bg-slate-100" name="ref" type="text" placeholder="Refrence" />
          <!-- Gender  -->
          <select name="gender" class="border w-full p-4 leading-tight bg-slate-100">
            <option hidden>Gender</option>
            <option value="male">Male</option>
            <option value="female">Female</option>
          </select>
        </div>
        <!-- Col 3 -->
        <div class="grid gap-2">
          <!-- Package  -->
          <select name="package" id="package" class="border w-full p-4 leading-tight bg-slate-100">
            <option hidden>Select a package</option>
            {% for package in packages %}
            <option value="{{package.id}} - {{package.price}}">{{package.name}} - {{package.price}} Taka</option>
            {% endfor %}
          </select>
          <!-- Address -->
          <textarea class="border w-full p-4 leading-tight bg-slate-100" name="address" placeholder="Address"
            required></textarea>
        </div>
        <!-- Col 4 -->
        <div class="grid gap-2">
          <!-- Payable Amount  -->
          <label for="">Total Amount</label>
          <input class="border w-full p-4 leading-tight bg-slate-100 disabled:bg-slate-400 disabled:cursor-not-allowed"
            name="payable_amount" id="payable_amount" type="number" value="0" placeholder="Payable Amount" disabled />
          <!-- Paying Amount  -->
          <label for="">Amount</label>
          <input class="border w-full p-4 leading-tight bg-slate-100 disabled:bg-slate-400 disabled:cursor-not-allowed" name="amount" id="amount" type="number" placeholder="0" disabled />
          <!-- Due Amount  -->
          <label for="">Due Amount</label>
          <input
            class="border w-full p-4 leading-tight bg-slate-100 disabled:bg-slate-400 disabled:cursor-not-allowed due_amount"
            type="number" value="0" disabled />
          <input class="due_amount" name="due_amount" value="0" hidden />
        </div>
        <div class="col-span-4">
          <button class="bg-blue-900 text-white font-bold py-2 px-4 w-full" type="submit">
            Add New Member
          </button>
        </div>
      </form>
    </div>
    <!-- List section starts  -->
    <div class="bg-gray-50 p-4 shadow-xl rounded-md">
      <div class="relative overflow-x-auto h-[28rem]">
        <table class="w-full">
          <thead class="text-sm uppercase bg-blue-900 text-gray-50 text-center">
            <tr>
              <th scope="col" class="px-6 py-3">Member ID</th>
              <th scope="col" class="px-6 py-3">Name</th>
              <th scope="col" class="px-6 py-3">phone</th>
              <th scope="col" class="px-6 py-3">Package</th>
              <th scope="col" class="px-6 py-3">Join Date</th>
              <th scope="col" class="px-6 py-3">Status</th>
              <th scope="col" class="px-6 py-3">Due/Advanced</th>
              <th scope="col" class="px-6 py-3">View</th>
            </tr>
          </thead>
          <tbody>
            {% for member in members %}
            <tr class="bg-white border text-sm text-center">
              <td class="px-6 py-4">{{member.memberId}}</td>
              <td class="px-6 py-4">{{member.name}}</td>
              <td class="px-6 py-4">{{member.phone}}</td>
              <td class="px-6 py-4">{{member.package.name}}</td>
              <td class="px-6 py-4">{{member.join_date}}</td>
              <td class="px-6 py-4">{{member.status}}</td>
              <td class="px-6 py-4">
                {% if member.due_payment < 0 %}
                {{ member.due_payment|abs_val }} Taka Advanced
                  {% else %}
                  {{member.due_payment}} Taka Due
                {% endif %}
                </td>
              <td class="px-6 py-4"><a class="underline" href="{% url "member:edit" member.id %}">View</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock body %}
{% block js %}
<script>
  $("document").ready(() => {
    // Package Select
    $("#package").change(e => {
      let price = e.target.value;
      price = price.split(' ');
      price = price[2];
      $("#payable_amount").val(`${price}`);
      $("#amount").removeAttr("disabled");
      $("#amount").val("");

      document.querySelectorAll(".due_amount").forEach(item => {
        item.value = `${price}`;
      })
    });
    // Amount Change
    $("#amount").on('input', (e) => {
      let pa = $("#payable_amount").val();
      let a = e.target.value;
      let val = (Number(pa) - Number(a)) > 0 ? (Number(pa) - Number(a)) : 0;
      document.querySelectorAll(".due_amount").forEach(item => {
        item.value = `${val}`;
      })
    })
  })
</script>
{% endblock js %}