FitMe/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "FitMe Administration"
admin.site.index_title = "FitMe"
admin.site.site_title = "ADMIN PANEL"


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("FitMeApp.urls")),
    path("user/", include("user.urls")),
    path("oauth", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from decorator_include import decorator_include
from django.contrib.auth.decorators import login_required
from .decorators import manager_access

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index , name='login'),
    path('logout/', views.logout, name='logout'),

    path('managerDashboard/', views.managerDashboard, name='managerDashboard'),
    path('employeeDashboard/', views.employeeDashboard, name='employeeDashboard'),
    path('coachDashboard/', views.coachDashboard, name='coachDashboard'),

    path('employeeAttendance/', views.employeeAttendance, name='employeeAttendance'),
    path('coachAttendance/<int:pk>', views.coachAttendance, name='coachAttendance'),

    path('user/', decorator_include(manager_access,"user.urls",namespace="user")),
    path('schedule/', decorator_include(manager_access,"schedule.urls",namespace="schedule")),
    path('equipment/', decorator_include(login_required,"equipment.urls",namespace="equipment")),
    path('package/', decorator_include(manager_access,"package.urls",namespace="package")),
    path('member/', decorator_include(login_required,"member.urls",namespace="member")),
    path('coach/', decorator_include(login_required,"coach.urls",namespace="coach")),
    path('transaction/', decorator_include(manager_access,"transaction.urls",namespace="transaction")),
]

equipment/urls.py
from django.urls import path
from . import views

app_name = "equipment"

urlpatterns = [
    path('', views.index , name='index'),
    path('edit/<int:pk>', views.edit , name='edit'),
    path('activity/', views.activity , name='activity'),
    path('book/', views.book , name='book'),
    path('active/<int:pk>', views.active , name='active'),
    path('deactivate/<int:pk>', views.deactivate , name='deactivate'),
    path('delete/<int:pk>', views.delete , name='delete'),
]

myProject/myProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("MyApp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equipment/models.py
from django.db import models
from schedule.models import Schedule
from django.utils.translation import gettext_lazy as _
from user.models import User

# Create your models here.

class EquipmentType(models.Model):
    name = models.CharField(_("Name"),max_length=50, null=True,blank=True)

    def __str__(self) -> str:
        return self.name

class Equipment(models.Model):
    name = models.CharField(_("Name"),max_length=50, null=True,blank=True)
    serial = models.CharField(_("Serial"),max_length=30,null=True,blank=True)
    equipmentType = models.ManyToManyField(EquipmentType,blank=True)
    maintenanceDate = models.DateField(_("Maintenance Date"), null=True,blank=True)
    is_available =  models.BooleanField(_("Availability Status"),default=True)
    url =  models.TextField(_("Url"),null=True,blank=True)
    
    price = models.FloatField(_("Price"),null=True,blank=True)
    brand = models.CharField(_("Brand"),max_length=50, null=True,blank=True)

    def __str__(self) -> str:
        return f'{self.name} | {self.serial}'
    
    def get_eqTypes(self):
        eqType = self.equipmentType.all()
        return eqType    

class EquipmentActivityTrack(models.Model):
    start_time = models.DateTimeField(_("Booking start"),null=True,blank=True)
    end_time = models.DateTimeField(_("Booking end"),null=True,blank=True)

    booked_by = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    booked_for =models.ForeignKey('member.Member', on_delete=models.CASCADE,null=True,blank=True)

    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE,null=True,blank=True)
    is_active =  models.BooleanField(_("Is Active"),default=True)

    def __str__(self) -> str:
        return f'{self.equipment} | {self.start_time} - {self.end_time}'

equipment/views.py
from django.shortcuts import render,redirect
from datetime import datetime, timedelta
from django.db.models import Q
from django.contrib import messages

from .models import Equipment,EquipmentType,EquipmentActivityTrack
from user.models import MetaData
from transaction.models import Credit
from member.models import Member
# Create your views here.
def index(request):
    eqs = Equipment.objects.all()
    eqTypes = EquipmentType.objects.all()
    eqActivities = EquipmentActivityTrack.objects.all()

    meta = MetaData.objects.last()
    if request.method == "POST":
        name = request.POST.get("name")
        brand = request.POST.get("brand")
        serial = request.POST.get("serial")
        price = request.POST.get("price")

        eqTypes_res = request.POST.getlist("eqType")


        eq = Equipment.objects.create(
            name = name,
            brand = brand,
            serial = serial,
            price = price,
            maintenanceDate = datetime.now()
        )
        for eqT in eqTypes_res:
            eq.equipmentType.add(eqT)
        
        timestamp = int(datetime.now().timestamp())

        costCondition = "store"
        
        if costCondition == "store":
            Credit.objects.create(
                trxId = 'FK-TRX-' + str(timestamp),
                reason = 'buy_equipment',
                amount = int(price),
                date = datetime.now(),
                is_equipment = True,
                equipment = eq
            )
            meta.funds -= int(price)
            meta.save()
        
    context = {
        'eqs':eqs,
        'eqTypes':eqTypes,
        'eqActivities':eqActivities
    }
    return render(request,'equipment/index.html',context)

def edit(request,pk):
    eq = Equipment.objects.get(id = pk)
    eqTypes = EquipmentType.objects.all()

    if request.method == "POST":
        name = request.POST.get("name")
        brand = request.POST.get("brand")
        eqTypes_res = request.POST.getlist("eqType")

        eq.name = name
        eq.brand = brand

            
        eq.save()

        eq.equipmentType.clear()
        for eqT in eqTypes_res:
            eq.equipmentType.add(eqT)

    context = {
        'eq':eq,
        'eqTypes':eqTypes
    }
    return render(request,"equipment/edit.html",context)

def activity(request):
    eqs = Equipment.objects.filter(is_available = True).order_by("-id")
    eqActivities = EquipmentActivityTrack.objects.all().order_by("start_time")[:5]
    members = Member.objects.filter(status=True).order_by("-id")



    if request.method == "POST":
        search = request.POST.get("search")
        eqs = Equipment.objects.filter(Q(name__icontains=search) | Q(serial__icontains=search),is_available = True)

    context = {
        'eqs': eqs,
        'eqActivities': eqActivities,
        'members': members
    }
    return render(request,"equipment/book.html",context)

def book(request):
    if request.method == "POST":
        serial = request.POST.get("serial")
        memId = request.POST.get("memId")
        date = request.POST.get("date")

        start_time = datetime.strptime(date, '%Y-%m-%dT%H:%M')
        end_time = start_time + timedelta(hours=1)

        today = datetime.now().date()
        input_date = start_time.date()
        day_gap = (input_date - today).days

        if day_gap < 0:
            messages.error(request,"Past Date Selected")
            return redirect("/equipment/activity/")
        elif day_gap > 1:
            messages.error(request,"Cannot book in 2  days advanced")
            return redirect("/equipment/activity/")

        # For member
        current_day = (datetime.now()).strftime('%A')

        selectedStartTime = start_time.time()
        selectedEndTime = end_time.time()
        try:
            eq = Equipment.objects.get(serial = serial)
            try:
                member = Member.objects.get(memberId=memId)
                if member.status == False:
                    messages.error(request,"Member Account Deactivated")      
                else:
                    # Check if member package supports selected time
                    check_start_time = False
                    check_end_time = False        
                    schedules = member.package.get_schedules_filter(current_day)
                    for sc in schedules:
                        if sc.start_time <= selectedStartTime <= sc.end_time:
                            check_start_time = True

                        if sc.start_time <= selectedEndTime <= sc.end_time:
                            check_end_time = True
                    if check_start_time == False or check_end_time == False:
                        messages.error(request,"Member Package Does not support selected time")
                        return redirect("/equipment/activity/")
                    # Check if member package supports selected equipment   
                    flag = False                
                    for eqT in eq.get_eqTypes():
                        for packageEqT in member.package.get_equipmentTypes():
                            if eqT.id == packageEqT.id:
                                flag = True
                    # Equipment and Member Correct  
                    if flag:
                        eqActivityCount = EquipmentActivityTrack.objects.filter(Q(start_time__range=(start_time,end_time)) | Q(end_time__range=(start_time,end_time)),equipment = eq,is_active = True).count()
                        if eqActivityCount != 0:
                            messages.error(request,"Schedule Already Booked")
                        else:
                            EquipmentActivityTrack.objects.create(
                                start_time = start_time,
                                end_time = end_time,
                                booked_by= request.user,
                                booked_for = member,
                                equipment = eq
                            )    
                    else:
                        messages.error(request,"Member Package Doesn't Support Selected Equipment")           
            except:
                messages.error(request,"Wrong Member Id")    
        except:
            messages.error(request,"Wrong Equipment Serial")
    return redirect("/equipment/activity/")

def deactivate(request,pk):
    eq = Equipment.objects.get(id = pk)
    eq.is_available = False
    eq.save()
    return redirect("/equipment/")

def active(request,pk):
    eq = Equipment.objects.get(id = pk)
    eq.is_available = True
    eq.maintenanceDate = datetime.now()
    eq.save()
    return redirect("/equipment/")

def delete(request,pk):
    Equipment.objects.get(id = pk).delete()
    return redirect("/equipment/")

templates/equipment/book.html
{% extends "../base.html" %}

{% block body %}
<div class="conponentSection p-5 sm:ml-64 bg-gray-200">
    <div class="componentWrapper">
        <!-- Entry Form starts  -->
        <div class="formSection bg-white p-4 rounded shadow-md mb-4">
            <h3 class="text-2xl font-bold mb-4">Search</h3>
            <form method="post">
                {% csrf_token %}
                <div>
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="search" type="text"
                        placeholder="Search For Equipment" />
                </div>
                <div class="mt-4">
                    <button class="bg-blue-900 text-white font-bold py-2 px-4 w-full" type="submit">
                        Search
                    </button>
                </div>
            </form>
        </div>     
        <div class="bg-gray-50 p-4 shadow-xl rounded-md mt-4">
            <h3 class="text-2xl font-semibold mb-4">Equipment List</h3>
            <div>
                <div class="relative overflow-x-auto">
                    <table class="w-full">
                        <thead class="text-sm uppercase bg-blue-900 text-gray-50 text-center">
                            <tr>
                                <th scope="col" class="px-6 py-3">Serial</th>
                                <th scope="col" class="px-6 py-3">Name</th>
                                <th scope="col" class="px-6 py-3">Maintenance Date</th>
                                <th scope="col" class="px-6 py-3">Equipment Type</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for eq in eqs %}
                                <tr class="bg-white border text-sm text-center">
                                    <td class="px-6 py-4">{{eq.serial}}</td>
                                    <td class="px-6 py-4">{{eq.name}}</td>
                                    <td class="px-6 py-4">{{eq.maintenanceDate}}</td>
                                    <td class="px-6 py-4">
                                        {% for eqT in eq.get_eqTypes %}
                                            {{eqT.name}},
                                        {% endfor %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="bg-gray-50 p-4 shadow-xl rounded-md mt-4">
            <h3 class="text-2xl font-semibold mb-4">Equipment Book History</h3>
            <div>
                <div class="relative overflow-x-auto">
                    <table class="w-full">
                        <thead class="text-sm uppercase bg-blue-900 text-gray-50 text-center">
                            <tr>
                                <th scope="col" class="px-6 py-3">Equipment</th>
                                <th scope="col" class="px-6 py-3">Duration</th>
                                <th scope="col" class="px-6 py-3">Booked By</th>
                                <th scope="col" class="px-6 py-3">Booked For</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for eq in eqActivities %}
                                <tr class="bg-white border text-sm text-center">
                                    <td class="px-6 py-4">{{eq.equipment.name}} | {{eq.equipment.serial}}</td>
                                    <td class="px-6 py-4">{{eq.start_time}} - {{eq.end_time}}</td>
                                    <td class="px-6 py-4">{{eq.booked_by.name}} | {{eq.booked_by.emp_id}}</td>
                                    <td class="px-6 py-4">{{eq.booked_for.name}} | {{eq.booked_for.memberId}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="bg-gray-50 p-4 shadow-xl rounded-md mt-4">
            {% for message in messages %}
                <div class="py-4 text-red-600 font-bold">
                    {{message}}
                </div>
            {% endfor %}
            <h3 class="text-2xl font-semibold mb-4">Book Equipment</h3>
            <form class="grid grid-cols-3 gap-4" method="post" autocomplete="off" action="/equipment/book/">
                {% csrf_token %}
                <!-- Serial -->
                <input class="border w-full p-4 leading-tight bg-slate-100" name="serial" type="text"
                placeholder="Equipment Serial" list="eqList" required />
                <datalist id="eqList">
                    {% for eq in eqs %}
                        <option value="{{eq.serial}}"> {{eq.name}} | {{eq.is_available}} </option>
                    {% endfor %}
                </datalist>
                <!-- For -->
                <input class="border w-full p-4 leading-tight bg-slate-100" name="memId" type="text"
                placeholder="Member Id" list="memberList" required />
                <datalist id="memberList">
                    {% for member in members %}
                        <option value="{{member.memberId}}"> {{member.name}} | {{member.package.name}} | {{member.status}} </option>
                    {% endfor %}
                </datalist>
                <!-- Date -->
                <input class="border w-full p-4 leading-tight bg-slate-100" name="date" type="datetime-local"
                placeholder="Date" required />
                <div class="col-span-3">
                    <button
                      class="bg-blue-900 text-white font-bold py-2 px-4 w-full"
                      type="submit">
                      Book
                    </button>
                  </div>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

templates/equipment/edit.html
{% extends "../base.html" %}

{% block body %}
   <!-- component sections starts  -->
   <div class="conponentSection p-5 sm:ml-64 bg-gray-200">
    <div class="componentWrapper">
            <!-- Entry Form starts  -->
            <div class="formSection bg-white px-10 py-8 rounded shadow-md mb-4">
                <h3 class="text-2xl font-bold mb-4">Edit Equipment Form</h3>
                <form class="grid grid-cols-3 gap-4" method="post">
                    {% csrf_token %}
                    <!-- Col 1 -->
                    <div class="grid gap-2">
                        <!-- Name -->
                        <input class="border w-full p-4 leading-tight bg-slate-100" name="name" type="text" placeholder="Name" required value="{{eq.name}}" />
                        <!-- Brand  -->
                        <input class="border w-full p-4 leading-tight bg-slate-100" name="brand" type="text" placeholder="Brand" value="{{eq.brand}}" />                     
                    </div>
                    <!-- Col 2 -->
                    <div class="grid gap-2">
                        <!-- Price -->
                        <input class="border w-full p-4 leading-tight bg-slate-100 disabled:cursor-not-allowed disabled:bg-slate-300" name="price" type="number" placeholder="Price" disabled value="{{eq.price}}" />                 
                         <!-- Serial -->
                         <input class="border w-full p-4 leading-tight bg-slate-100 disabled:cursor-not-allowed disabled:bg-slate-300" name="serial" type="text" placeholder="Serial" disabled value="{{eq.serial}}" />
                    </div>
                    <!-- Col 3 -->
                    <div class="grid gap-2">               
                        <!-- Equipment Type  -->
                        <select name="eqType" class="border w-full p-4 leading-tight bg-slate-100" multiple>
                            <optgroup label="Selected">
                                {% for eqT in eq.get_eqTypes  %}                               
                                    <option selected value="{{eqT.id}}">{{eqT.name}}</option>
                                {% endfor %}                          
                            </optgroup>
                            <optgroup label="All">
                            {% for eqt in eqTypes %}
                                     <option value="{{eqt.id}}">{{eqt}}</option>
                            {% endfor %}
                            </optgroup>
                        </select>      
                    </div>
                    <div>
                        <button
                          class="bg-blue-900 text-white font-bold py-2 px-4 w-full"
                          type="submit">
                          Update
                        </button>
                    </div>
                    <div>
                        {% if eq.is_available %}
                        <a href="{% url "equipment:deactivate"  eq.id %}" class="bg-yellow-900 text-white font-bold py-2 px-4 w-full inline-block text-center cursor-pointer">
                            Maintenence Mode
                        </a>
                        {% else %}
                        <a href="{% url "equipment:active"  eq.id %}" class="bg-green-900 text-white font-bold py-2 px-4 w-full inline-block text-center cursor-pointer">
                            Make Available
                        </a>
                    {% endif %}
                    </div>
                    <div>
                        <a  href="{% url "equipment:delete"  eq.id %}"  class="bg-red-900 text-white font-bold py-2 px-4 w-full inline-block text-center cursor-pointer">
                            Delete Equipment
                        </a>
                    </div>
                </form>
            </div>
    </div>
  </div>
{% endblock body %}

templates/equipment/index.html
{% extends "../base.html" %}

{% block body %}
   <!-- component sections starts  -->
   <div class="conponentSection p-5 sm:ml-64 bg-gray-200">
    <div class="componentWrapper">
        <!-- Entry Form starts  -->
        <div class="formSection bg-white p-4 rounded shadow-md mb-4">
            <h3 class="text-2xl font-bold mb-4">New Equipment Form</h3>
            <form class="grid grid-cols-2 gap-4" method="post">
              {% csrf_token %}
                <!-- Col 1 -->
                <div class="grid gap-2">
                    <!-- Name -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="name" type="text" placeholder="Name" required />
                    <!-- Brand  -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="brand" type="text" placeholder="Brand" />
                    <!-- Serial -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="serial" type="text" placeholder="Serial" required />
                </div>
                <!-- Col 2 -->
                <div class="grid gap-2">
                    <!-- Price -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="price" type="number" placeholder="Price" required />                 
                    <!-- Equipment Type  -->
                    <select name="eqType" class="border w-full p-4 leading-tight bg-slate-100" multiple required>
                      <option hidden>Equipment Type</option>
                      {% for eq in eqTypes %}
                        <option value="{{eq.id}}">{{eq.name}}</option>
                      {% endfor %}
                    </select>       
                </div>
                <div class="col-span-3">
                    <button
                      class="bg-blue-900 text-white font-bold py-2 px-4 w-full"
                      type="submit">
                      Add New Equipment
                    </button>
                  </div>
            </form>
        </div>
      <!-- List section starts  -->
      <div class="bg-gray-50 p-4 shadow-xl rounded-md">
        <div class="relative overflow-x-auto">
          <table class="w-full">
            <thead
              class="text-sm uppercase bg-blue-900 text-gray-50 text-center"
            >
              <tr>
                <th scope="col" class="px-6 py-3">Serial</th>
                <th scope="col" class="px-6 py-3">Name</th>
                <th scope="col" class="px-6 py-3">Brand</th>
                <th scope="col" class="px-6 py-3">Status</th>
                <th scope="col" class="px-6 py-3">View</th>
              </tr>
            </thead>
            <tbody>
              {% for eq in eqs %}
              <tr class="bg-white border text-sm text-center">
                <td class="px-6 py-4">{{eq.serial}}</td>
                <td class="px-6 py-4">{{eq.name}}</td>
                <td class="px-6 py-4">{{eq.brand}}</td>
                <td class="px-6 py-4">{{eq.is_available}}</td>
                <td class="px-6 py-4"><a class="underline" href="{% url "equipment:edit" eq.id %}">View</a></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
        <!-- Track starts  -->
        <div class="bg-gray-50 p-4 shadow-xl rounded-md mt-4">
          <h3 class="text-2xl font-bold mb-4">Equipment Activity Track</h3>
          <div class="relative overflow-x-auto">
            <table class="w-full">
              <thead
                class="text-sm uppercase bg-blue-900 text-gray-50 text-center"
              >
                <tr>
                  <th scope="col" class="px-6 py-3">Serial</th>
                  <th scope="col" class="px-6 py-3">Name</th>
                  <th scope="col" class="px-6 py-3">Booked By</th>
                  <th scope="col" class="px-6 py-3">Booked To</th>
                  <th scope="col" class="px-6 py-3">Duration</th>
                </tr>
              </thead>
              <tbody>
                {% for eq in eqActivities %}
                  <tr class="bg-white border text-sm text-center">
                    <td class="px-6 py-4">{{eq.equipment.serial}}</td>
                    <td class="px-6 py-4">{{eq.equipment.name}}</td>
                    <td class="px-6 py-4">{{eq.booked_by.name}}</td>
                    <td class="px-6 py-4">{{eq.booked_for.name}}</td>
                    <td class="px-6 py-4">{{eq.start_time}} - {{eq.end_time}}</td>            
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
    </div>
  </div>
{% endblock body %}