FitMe/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "FitMe Administration"
admin.site.index_title = "FitMe"
admin.site.site_title = "ADMIN PANEL"


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("FitMeApp.urls")),
    path("user/", include("user.urls")),
    path("oauth", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coach/urls.py
from django.urls import path
from . import views

app_name = "coach"

urlpatterns = [
    path('', views.index , name='index'),
    path('edit/<int:pk>', views.edit , name='edit'),
    path('attendance/<int:pk>/<int:id>', views.attendance , name='attendance'),
    path('activity/', views.activity , name='activity'),
    path('book/', views.book , name='book'),
    path('active/<int:pk>', views.active , name='active'),
    path('deactivate/<int:pk>', views.deactivate , name='deactivate'),
    path('delete/<int:pk>', views.delete , name='delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from decorator_include import decorator_include
from django.contrib.auth.decorators import login_required
from .decorators import manager_access

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index , name='login'),
    path('logout/', views.logout, name='logout'),

    path('managerDashboard/', views.managerDashboard, name='managerDashboard'),
    path('employeeDashboard/', views.employeeDashboard, name='employeeDashboard'),
    path('coachDashboard/', views.coachDashboard, name='coachDashboard'),

    path('employeeAttendance/', views.employeeAttendance, name='employeeAttendance'),
    path('coachAttendance/<int:pk>', views.coachAttendance, name='coachAttendance'),

    path('user/', decorator_include(manager_access,"user.urls",namespace="user")),
    path('schedule/', decorator_include(manager_access,"schedule.urls",namespace="schedule")),
    path('equipment/', decorator_include(login_required,"equipment.urls",namespace="equipment")),
    path('package/', decorator_include(manager_access,"package.urls",namespace="package")),
    path('member/', decorator_include(login_required,"member.urls",namespace="member")),
    path('coach/', decorator_include(login_required,"coach.urls",namespace="coach")),
    path('transaction/', decorator_include(manager_access,"transaction.urls",namespace="transaction")),
]

member/urls.py
from django.urls import path
from . import views

app_name = "member"

urlpatterns = [
    path('', views.index , name='index'),
    path('admin_view/', views.adminView , name='admin_view'),
    path('edit/<int:pk>', views.edit , name='edit'),
    path('payment_history/<int:pk>/<str:month>/<int:year>', views.paymentHistory , name='payment_history'),
    path('bill/', views.bill , name='bill'),
    path('pay/', views.pay , name='pay'),
    path('active/<int:pk>', views.active , name='active'),
    path('deactivate/<int:pk>', views.deactivate , name='deactivate'),
    path('delete/<int:pk>', views.delete , name='delete'),
]

myProject/myProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("MyApp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gym Management System - Fitness Kingdom</title>
    {% comment %} <meta http-equiv="refresh" content="5" > {% endcomment %}
     <!-- tailwind cdn  -->
     <script src="https://cdn.tailwindcss.com"></script>

     <link rel="stylesheet"
     href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">

     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    {% include "sidebar.html" %}
    {% block body %}
    {% endblock body %}

    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    {% block js %}{% endblock js %}
</body>
</html>

templates/sidebar.html
<!-- dashboard section starts  -->
<div
  class="dashboardContainer fixed top-0 left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0"
  aria-label="Sidebar"
>
  <div class="h-full px-3 py-4 overflow-y-auto bg-blue-900 relative">
    <!-- dashboard top section  -->
    <div
      class="dashBoardTop mb-8 flex flex-col justify-center items-center text-gray-50 border-b-2 border-gray-200 pb-3"
    >
      <div class="iconSection pb-1">
        <i class='bx bx-user text-6xl text-white'></i>
      </div>

      <div class="bottomText text-xl text-center leading-[1.5rem]">
        <h1>Welcome,</h1>
        <h1 class="font-semibold">{{request.user.username}}</h1>
      </div>
    </div>
    <!-- dashboard top section  -->

    <!-- dashboard lists  -->
    <div class="dashBoardLinks">
      <ul class="space-y-2 font-medium">
        {% if request.user.is_manager %}
        <li>
            <a
            href="{% url "managerDashboard" %}"
            class="border border-gray-50 flex justify-center items-center p-2 text-gray-100 rounded hover:bg-gray-100 hover:text-gray-900"
            >
            <p class="ms-3">Dashboard</p>
          </a>        
        </li>
        <li>
          <a
            href="{% url "user:index" %}"
            class="border border-gray-50 flex justify-center items-center p-2 text-gray-100 rounded hover:bg-gray-100 hover:text-gray-900"
          >
            <p class="ms-3">Employee</p>
          </a>
        </li>
        <!--  -->
        <li>
          <a
            href="{% url "member:admin_view" %}"
            class="border border-gray-50 flex justify-center items-center p-2 text-gray-100 rounded hover:bg-gray-100 hover:text-gray-900"
          >
            <p class="ms-3">Member</p>
          </a>
        </li>
        <!--  -->
        <li>
          <a
            href="{% url "coach:index" %}"
            class="border border-gray-50 flex justify-center items-center p-2 text-gray-100 rounded hover:bg-gray-100 hover:text-gray-900"
          >
            <p class="ms-3">Coach</p>
          </a>
        </li>
        <!--  -->
        <li>
          <a
            href="{% url "equipment:index" %}"
            class="border border-gray-50 flex justify-center items-center p-2 text-gray-100 rounded hover:bg-gray-100 hover:text-gray-900"
          >
            <p class="ms-3">Equipment</p>
          </a>
        </li>
        <!--  -->
        <li>
          <a
            href="{% url "schedule:index" %}"
            class="border border-gray-50 flex justify-center items-center p-2 text-gray-100 rounded hover:bg-gray-100 hover:text-gray-900"
          >
            <p class="ms-3">Schedule</p>
          </a>
        </li>
        <!--  -->
        <li>
          <a
            href="{% url "package:index" %}"
            class="border border-gray-50 flex justify-center items-center p-2 text-gray-100 rounded hover:bg-gray-100 hover:text-gray-900"
          >
            <p class="ms-3">Package</p>
          </a>
        </li>
        <!--  -->
        <li>
          <a
            href="{% url "transaction:index" %}"
            class="border border-gray-50 flex justify-center items-center p-2 text-gray-100 rounded hover:bg-gray-100 hover:text-gray-900"
          >
            <p class="ms-3">Transaction</p>
          </a>
        </li>
          {% else %}
          <li>
          <a
          href="{% url "employeeDashboard" %}"
          class="border border-gray-50 flex justify-center items-center p-2 text-gray-100 rounded hover:bg-gray-100 hover:text-gray-900"
          >
          <p class="ms-3">Dashboard</p>
        </a>
        </li>
        <li>
          <a
            href="{% url "member:index" %}"
            class="border border-gray-50 flex justify-center items-center p-2 text-gray-100 rounded hover:bg-gray-100 hover:text-gray-900"
          >
            <p class="ms-3">Members</p>
          </a>
        </li>
        <!--  -->     
      {% endif %}  
      </ul>
    </div>

    <!-- dashboard lists ends   -->

    <!-- logout  button starts  -->
    <div class="logoutSection absolute bottom-3 left-3">
      <div
        class="logOutWrapper flex justify-between items-center cursor-pointer"
      >
        <a href="{% url "logout" %}" class="flex items-center justify-center logoutIcon bg-blue-400 w-10 h-10 rounded-full shadow-lg">
          <i class='bx bx-log-out text-2xl text-white'></i>
        </a>
        <p class="text-lg pl-2 font-semibold text-gray-50">Logout</p>
      </div>
    </div>
    <!-- logout  button ends  -->
  </div>
</div>
<!-- dashboard section ends  -->