FitMe/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "FitMe Administration"
admin.site.index_title = "FitMe"
admin.site.site_title = "ADMIN PANEL"


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("FitMeApp.urls")),
    path("user/", include("user.urls")),
    path("oauth", include("social_django.urls", namespace="social")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coach/urls.py
from django.urls import path
from . import views

app_name = "coach"

urlpatterns = [
    path('', views.index , name='index'),
    path('edit/<int:pk>', views.edit , name='edit'),
    path('attendance/<int:pk>/<int:id>', views.attendance , name='attendance'),
    path('activity/', views.activity , name='activity'),
    path('book/', views.book , name='book'),
    path('active/<int:pk>', views.active , name='active'),
    path('deactivate/<int:pk>', views.deactivate , name='deactivate'),
    path('delete/<int:pk>', views.delete , name='delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from decorator_include import decorator_include
from django.contrib.auth.decorators import login_required
from .decorators import manager_access

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index , name='login'),
    path('logout/', views.logout, name='logout'),

    path('managerDashboard/', views.managerDashboard, name='managerDashboard'),
    path('employeeDashboard/', views.employeeDashboard, name='employeeDashboard'),
    path('coachDashboard/', views.coachDashboard, name='coachDashboard'),

    path('employeeAttendance/', views.employeeAttendance, name='employeeAttendance'),
    path('coachAttendance/<int:pk>', views.coachAttendance, name='coachAttendance'),

    path('user/', decorator_include(manager_access,"user.urls",namespace="user")),
    path('schedule/', decorator_include(manager_access,"schedule.urls",namespace="schedule")),
    path('equipment/', decorator_include(login_required,"equipment.urls",namespace="equipment")),
    path('package/', decorator_include(manager_access,"package.urls",namespace="package")),
    path('member/', decorator_include(login_required,"member.urls",namespace="member")),
    path('coach/', decorator_include(login_required,"coach.urls",namespace="coach")),
    path('transaction/', decorator_include(manager_access,"transaction.urls",namespace="transaction")),
]

myProject/myProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("MyApp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myProject/user/urls.py
from django.urls import path, include
from django.conf import settings
from . import views
from django.conf.urls.static import static
from django.contrib.auth import views as auth

urlpatterns = [
    path("TrainerRegister/", views.TrainerRegister, name="TrainerRegister"),
    path("logout/", auth.LogoutView.as_view(template_name="index.html"), name="logout"),
    path("TraineeRegister/", views.TraineeRegister, name="TraineeRegister"),
    path(
        "TraineeProfileUpdate/", views.TraineeProfileUpdate, name="TraineeProfileUpdate"
    ),
    path("TraineeProfile/", views.TraineeProfile, name="TraineeProfile"),
]

myProject/user/models.py
from typing import Any, Union
from myProject import settings
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from PIL import Image
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template


class Trainer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    trainer = models.BooleanField("trainer", default=True)
    approve = models.BooleanField(default=False)
    image = models.ImageField(
        default="profile_pics/default.jpg", upload_to="profile_pics"
    )

    def __str__(self):
        return f"{self.user.username} Profile"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.approve:
            ######################### mail system #####################################
            try:
                email = self.user.email
                print("\n\n\n", email, settings.EMAIL_HOST_USER)
                htmly = get_template("user/Email.html")
                d = {"username": self.user.username}
                subject = "Welcome to FitMe, you are approved by admin"
                from_email = settings.EMAIL_HOST_USER
                to = email
                html_content = htmly.render(d)
                msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
                msg.attach_alternative(html_content, "text/html")
                msg.send()
            except:
                print("email not working")

        img = Image.open(self.image.path)
        print("\n\n\n  -->  try saving image")
        width, height = img.size
        if height >= 300 or width >= 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

    class Meta:
        db_table = "trainer"


class Trainee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    trainee = models.BooleanField("trainee", default=True)
    trainer_ass = models.ForeignKey(
        Trainer, blank=True, null=True, on_delete=models.SET_NULL
    )
    phone = models.CharField(max_length=11, unique=True, null=True, blank=True)
    height = models.DecimalField(max_digits=5, decimal_places=2)  # Adjusted precision
    age = models.IntegerField()
    current_weight = models.DecimalField(max_digits=5, decimal_places=5)  # Adjusted precision
    body_fat = models.IntegerField()
    goal_weight = models.DecimalField(max_digits=5, decimal_places=2)  # Adjusted precision
    health_condition = models.CharField(max_length=50)
    dob = models.DateField(default=datetime.now)
    gender = models.CharField(max_length=6, default="Male", null=True, blank=True)
    image = models.ImageField(
        default="profile_pics/default.jpg", upload_to="profile_pics"
    )

    def __str__(self):
        return f"{self.user.username} Profile"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        print("\n\n\n  -->  try saving image")
        width, height = img.size
        if height >= 300 or width >= 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            print("no error")
            img.save(self.image.path)
        else:
            print("no error saving")
            img.save(self.image.path)

    class Meta:
        db_table = "trainee"

myProject/user/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django import forms


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2",
        ]


class TraineeRegisterForm(ModelForm):
    class Meta:
        model = Trainee
        exclude = ("trainee", "user")


class TrainerRegisterForm(ModelForm):
    class Meta:
        model = Trainer
        fields = []


class TraineeUpdateForm(ModelForm):
    class Meta:
        model = Trainee
        exclude = ("trainee", "user")


class TrainerUpdateForm(ModelForm):
    class Meta:
        model = Trainer
        fields = "__all__"

myProject/user/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .models import *
from .forms import *
from django.contrib.auth.models import User

# for email send when register############################

from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context
from myProject import settings


########### register here #####################################
def TraineeRegister(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        Tform = TraineeRegisterForm(request.POST, request.FILES)
        if form.is_valid() and Tform.is_valid():
            user = form.save()
            profile = Tform.save(commit=False)
            profile.user = user
            profile.save()

            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")
            ######################### mail system ####################################
            htmly = get_template("user/Email.html")
            d = {"username": username}
            subject, from_email, to = (
                "welcome to FitMe",
                settings.EMAIL_HOST_USER,
                email,
            )
            html_content = htmly.render(d)
            msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
            msg.attach_alternative(html_content, "text/html")
            try:
                msg.send()
            except:
                print("email not working")
                pass
            ##################################################################
            messages.success(
                request, f"Your account has been created! You are now able to log in"
            )
            return redirect("index")
    else:
        form = UserRegisterForm()
        Tform = TraineeRegisterForm()

    return render(request, "user/register.html", {"form": form, "tform": Tform})


############################## TrainerRegister ###############################################


def TrainerRegister(request):
    # TrainerRegisterForm
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        Tform = TrainerRegisterForm(request.POST)
        if form.is_valid() and Tform.is_valid():
            user = form.save()
            profile = Tform.save(commit=False)
            profile.user = user
            profile.save()

            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")
            ######################### mail system ####################################
            htmly = get_template("user/Email.html")
            d = {"username": username}
            subject, from_email, to = (
                "welcome to FitMe",
                "settings.EMAIL_HOST_USER",
                email,
            )
            html_content = htmly.render(d)
            msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
            msg.attach_alternative(html_content, "text/html")
            try:
                msg.send()
            except:
                print("email not working")
                pass
            ##################################################################
            messages.success(
                request, f"Your account has been created! ask admin to approve "
            )
            return redirect("index")
    else:
        form = UserRegisterForm()
        Tform = TrainerRegisterForm()

    return render(request, "user/register.html", {"form": form, "tform": Tform})


################################## update ####################################


@login_required
def TraineeProfileUpdate(request):
    if request.method == "POST":
        form = TraineeUpdateForm(request.POST,request.FILES,instance=request.user.trainee)
        print('\n\n\n\n\n-->',form.errors)
        if form.is_valid():
            form.save()
            messages.success(request, f"profile is updated")
            return redirect("TraineeProfile")

    form = TraineeUpdateForm(instance=request.user.trainee)

    data = {
        "form": form,
        "profile_pic": request.user.trainee.image.url,
        "title": "profile update for {}".format(request.user),
    }
    return render(request, "user/TraineeProfileUpdate.html", data)


############################## Trainee Profile #####################################


@login_required
def TraineeProfile(request):
    data = {"profile_pic": request.user.trainee.image.url}
    return render(request, "user/profile.html", data)

user/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from .models import *
from .forms import *
from django.contrib.auth.models import User

# for email send when register############################

from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context
from FitMe import settings


########### register here #####################################
def TraineeRegister(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        Tform = TraineeRegisterForm(request.POST, request.FILES)
        if form.is_valid() and Tform.is_valid():
            user = form.save()
            profile = Tform.save(commit=False)
            profile.user = user
            profile.save()

            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")
            ######################### mail system ####################################
            htmly = get_template("user/Email.html")
            d = {"username": username}
            subject, from_email, to = (
                "welcome to FitMe",
                settings.EMAIL_HOST_USER,
                email,
            )
            html_content = htmly.render(d)
            msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
            msg.attach_alternative(html_content, "text/html")
            try:
                msg.send()
            except:
                print("email not working")
                pass
            ##################################################################
            messages.success(
                request, f"Your account has been created! You are now able to log in"
            )
            return redirect("index")
    else:
        form = UserRegisterForm()
        Tform = TraineeRegisterForm()

    return render(request, "user/register.html", {"form": form, "tform": Tform})


############################## TrainerRegister ###############################################


def TrainerRegister(request):
    # TrainerRegisterForm
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        Tform = TrainerRegisterForm(request.POST)
        if form.is_valid() and Tform.is_valid():
            user = form.save()
            profile = Tform.save(commit=False)
            profile.user = user
            profile.save()

            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")
            ######################### mail system ####################################
            htmly = get_template("user/Email.html")
            d = {"username": username}
            subject, from_email, to = (
                "welcome to FitMe",
                "settings.EMAIL_HOST_USER",
                email,
            )
            html_content = htmly.render(d)
            msg = EmailMultiAlternatives(subject, html_content, from_email, [to])
            msg.attach_alternative(html_content, "text/html")
            try:
                msg.send()
            except:
                print("email not working")
                pass
            ##################################################################
            messages.success(
                request, f"Your account has been created! ask admin to approve "
            )
            return redirect("index")
    else:
        form = UserRegisterForm()
        Tform = TrainerRegisterForm()

    return render(request, "user/register.html", {"form": form, "tform": Tform})


################################## update ####################################


@login_required
def TraineeProfileUpdate(request):
    if request.method == "POST":
        form = TraineeUpdateForm(request.POST,request.FILES,instance=request.user.trainee)
        print('\n\n\n\n\n-->',form.errors)
        if form.is_valid():
            form.save()
            messages.success(request, f"profile is updated")
            return redirect("TraineeProfile")

    form = TraineeUpdateForm(instance=request.user.trainee)

    data = {
        "form": form,
        "profile_pic": request.user.trainee.image.url,
        "title": "profile update for {}".format(request.user),
    }
    return render(request, "user/TraineeProfileUpdate.html", data)


############################## Trainee Profile #####################################


@login_required
def TraineeProfile(request):
    data = {"profile_pic": request.user.trainee.image.url}
    return render(request, "user/profile.html", data)

templates/user/edit.html
{% extends "../base.html" %}

{% block body %}
<!-- component sections starts  -->
<div class="conponentSection p-5 sm:ml-64 bg-gray-200">
    <div class="componentWrapper">
        <!-- Form starts  -->
        <div class="formSection bg-white px-10 py-8 rounded shadow-md mb-4">
            <h3 class="text-2xl font-bold mb-4">Edit Employee</h3>
            <form class="grid grid-cols-3 gap-4" method="post">
                {% csrf_token %}
                <!-- Col 1 -->
                <div class="grid gap-2">
                    <!-- User name -->
                    <input
                        class="border w-full p-4 leading-tight bg-slate-100 disabled:cursor-not-allowed disabled:bg-slate-300"
                        name="username" type="text" placeholder="Username" value={{employee.username}} disabled />
                    <!-- Name -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="name" type="text"
                        placeholder="Name" value="{{employee.name}}" required />
                    <!-- Salary -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="salary" type="number"
                        placeholder="Salary" required value={{employee.salary}} />
                </div>
                <!-- Col 2 -->
                <div class="grid gap-2">
                    <!-- Employee ID -->
                    <input
                        class="border w-full p-4 leading-tight bg-slate-100 disabled:cursor-not-allowed disabled:bg-slate-300"
                        name="empId" type="text" placeholder="Employee ID" disabled value={{employee.emp_id}} />
                    <!-- Phone -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="phone" type="tel"
                        placeholder="Phone" required value={{employee.phone}} />
                    <!-- NID -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="nid" type="text" placeholder="NID"
                        required value={{employee.nid}} />
                </div>
                <!-- Col 3 -->
                <div class="grid gap-2">
                    <!-- Address -->
                    <textarea class="border w-full p-4 leading-tight bg-slate-100" name="address" placeholder="Address"
                        required>{{employee.address}}</textarea>
                    <!-- Password  -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="password" type="text"
                        placeholder="Password" />
                </div>
                <!-- Schedule -->
                <div class="col-span-3">
                    <span class="font-semibold mb-1 inline-block">Select Schedule</span>
                    <select name="schedule" multiple class="border w-full p-4 leading-tight bg-slate-100">
                        <optgroup label="Selected">
                            {% for schedule in employee.get_schedules %}
                            <option selected value="{{schedule.id}}">{{schedule}}</option>
                            {% endfor %}
                        </optgroup>
                        <optgroup label="All">
                            {% for schedule in schedules %}
                            <option value="{{schedule.id}}">{{schedule}}</option>
                            {% endfor %}
                        </optgroup>
                    </select>
                </div>
                <div>
                    <button class="bg-blue-900 text-white font-bold py-2 px-4 w-full" type="submit">
                        Update
                    </button>
                </div>
                <div>
                    {% if employee.is_active %}
                    <a href="{% url "user:deactivate" employee.id %}"
                        class="bg-yellow-900 text-white font-bold py-2 px-4 w-full inline-block text-center cursor-pointer">
                        Deactivate Account
                    </a>
                    {% else %}
                    <a href="{% url "user:active" employee.id %}"
                        class="bg-green-900 text-white font-bold py-2 px-4 w-full inline-block text-center cursor-pointer">
                        Activate Account
                    </a>
                    {% endif %}
                </div>
                <div>
                    <a href="{% url "user:delete" employee.id %}"
                        class="bg-red-900 text-white font-bold py-2 px-4 w-full inline-block text-center cursor-pointer">
                        Delete Account
                    </a>
                </div>
            </form>
        </div>
        <!-- Attendance -->
        <section class="bg-gray-50 w-full p-4 shadow-xl rounded-md mt-4">
            <div class="flex justify-between">
                <h3 class="text-2xl font-bold">Attendance</h3>
            </div>
            <div class="relative overflow-x-auto mt-4">
                <table class="w-full">
                    <thead class="text-sm uppercase bg-blue-900 text-gray-50 text-center">
                        <tr>
                            <th scope="col" class="px-6 py-3">Date</th>
                            <th scope="col" class="px-6 py-3">Attendance Status</th>
                            <th scope="col" class="px-6 py-3">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for att in attendance %}
                        <tr class="bg-white border text-sm text-center">
                            <td class="px-6 py-4">{{att.date}}</td>
                            <td class="px-6 py-4">
                                {% if att.attendance %}
                                    Present
                                    {% else %}
                                    Absent
                                {% endif %}
                            </td>
                            <td>
                                <a class="underline" href="{% url "user:attendance" employee.id att.id %}">
                                {% if att.attendance %}
                                    Mark as absent
                                    {% else %}
                                    Mark as present
                                {% endif %}
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </section>
            <!-- Transaction -->
            <section class="bg-gray-50 w-full p-4 shadow-xl rounded-md mt-4">
            <div class="flex justify-between">
                <h3 class="text-2xl font-bold">Salary History</h3>
                <span>Due Salary: {{employee.due}} Taka</span>
            </div>
            <div>
                Join Date: {{employee.join_date}}
            </div>
            <div class="relative overflow-x-auto mt-4">
                <table class="w-full">
                    <thead class="text-sm uppercase bg-blue-900 text-gray-50 text-center">
                        <tr>
                            <th scope="col" class="px-6 py-3">Date</th>
                            <th scope="col" class="px-6 py-3">Amount</th>
                            <th scope="col" class="px-6 py-3">Reason</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for salary in salaries %}
                        <tr class="bg-white border text-sm text-center">
                            <td class="px-6 py-4">{{salary.date}}</td>
                            <td class="px-6 py-4">{{salary.amount}}</td>
                            <td> {{salary.reason}} </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </section>
    </div>
</div>
{% endblock body %}

templates/user/index.html
{% extends "../base.html" %}

{% block body %}
   <!-- component sections starts  -->
   <div class="conponentSection p-5 sm:ml-64 bg-gray-200">
    <div class="componentWrapper">
        <!-- Entry Form starts  -->
        <div class="formSection bg-white p-4 rounded shadow-md mb-4">
            <h3 class="text-2xl font-bold mb-4">New Employee Form</h3>
            <form class="grid grid-cols-3 gap-4" method="post">
              {% csrf_token %}
                <!-- Col 1 -->
                <div class="grid gap-2">
                    <!-- User name -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="username" type="text" placeholder="Username" required />
                    <!-- Name -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="name" type="text" placeholder="Name" required />
                    <!-- DOB  -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="dob" type="date" required />
                </div>
                <!-- Col 2 -->
                <div class="grid gap-2">
                    <!-- Phone -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="phone" type="tel" placeholder="Phone" required />
                    <!-- NID -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="nid" type="text" placeholder="NID" required />
                    <!-- Gender  -->
                    <select name="gender" class="border w-full p-4 leading-tight bg-slate-100">
                        <option hidden>Gender</option>
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                    </select>
                </div>
                <!-- Col 3 -->
                <div class="grid gap-2">
                    <!-- Salary -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="salary" type="number" placeholder="Salary" required />
                    <!-- Address -->
                    <textarea class="border w-full p-4 leading-tight bg-slate-100" name="address" placeholder="Address" required ></textarea>
                    <!-- Password  -->
                    <input class="border w-full p-4 leading-tight bg-slate-100" name="password" type="text" placeholder="Password" required />
                </div>
                <!-- Schedule -->
                <div class="col-span-3">
                    <span class="font-semibold mb-1 inline-block">Select Schedule</span>
                    <select name="schedule" multiple class="border w-full p-4 leading-tight bg-slate-100" required>
                        {% for schedule in schedules %}
                          <option value="{{schedule.id}}">{{schedule}}</option>
                        {% endfor %}
                      </select>
                </div>
                <div class="col-span-3">
                    <button
                      class="bg-blue-900 text-white font-bold py-2 px-4 w-full"
                      type="submit">
                      Add New Employee
                    </button>
                  </div>
            </form>
        </div>
      </div>
      <!-- List section starts  -->
      <div class="bg-gray-50 p-4 shadow-xl rounded-md">
        <div class="relative overflow-x-auto h-[28rem]">
          <table class="w-full">
            <thead
              class="text-sm uppercase bg-blue-900 text-gray-50 text-center"
            >
              <tr>
                <th scope="col" class="px-6 py-3">EMP ID</th>
                <th scope="col" class="px-6 py-3">Name</th>
                <th scope="col" class="px-6 py-3">phone</th>
                <th scope="col" class="px-6 py-3">salary</th>
                <th scope="col" class="px-6 py-3">Status</th>
                <th scope="col" class="px-6 py-3">View</th>
              </tr>
            </thead>
            <tbody>
              {% for employee in employees %}
              <tr class="bg-white border text-sm text-center">
                <td class="px-6 py-4">{{employee.emp_id}}</td>
                <td class="px-6 py-4">{{employee.name}}</td>
                <td class="px-6 py-4">{{employee.phone}}</td>
                <td class="px-6 py-4">{{employee.salary}}</td>
                <td class="px-6 py-4">{{employee.is_active}}</td>
                <td class="px-6 py-4"><a class="underline" href="{% url "user:edit" employee.id %}">View</a></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock body %}